spring:
  profiles:
    active: pro
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_raillery?characterEncoding=utf-8
        username: root
        password: czcat
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  http:
    multipart:
      max-file-size: 10MB #设置文件上传时单个文件的大小限制
      max-request-size: 100MB #设置文件上传时总文件大小限制

  thymeleaf:
    prefix: classpath:/templates/  #指定了静态文件的地址

upload:
  path: Files #文件上传路径

server:
  session-timeout: 10 # session最大超时时间(分钟)，默认为30s


